
public class botonMaestro extends javax.swing.JPanel {

    /**
     * Creates new form maestroIndividualDePopUp
     */
    String nombre;
    String conrato;
    String matricula;
    popUpMaestros popup;
    int numMae;
    public botonMaestro(String nombre, String contrato, String matricula,popUpMaestros popup,int numMae) {
        initComponents();
        this.nombre=nombre;
        this.matricula=matricula;
        this.conrato=conrato;
        jLabel1.setText(nombre);
        jLabel2.setText(contrato);
        this.popup=popup;
        this.numMae=numMae;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        infoBoton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAESTRO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, 201, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIPO_CONTRATO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 201, -1));

        infoBoton.setText("i");
        infoBoton.setToolTipText("");
        infoBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBotonActionPerformed(evt);
            }
        });
        add(infoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void infoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoBotonActionPerformed
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.popup.nomMae(this.nombre);
        this.popup.borrarMaestro(numMae);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton infoBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
