
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import java.net.URL;
public class botonMaterias extends javax.swing.JPanel {

    /**
     * Creates new form botonMaterias
     */
    public boolean desplegado=false;
    public int numMat;
    String materia;
    int horasSem;
    String docente;
    HorarioGrupo horario;
    public botonMaterias( String materia,int horasSem, HorarioGrupo horario,int numMat) {
        initComponents();
        this.horasSem=horasSem;
        this.materia=materia;
        jLabel3.setText(materia);
        jLabel2.setText(String.valueOf(horasSem));
        this.horario=horario;
        this.numMat=numMat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonDesplegar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECCIONAR DOCENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MATERIA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 47));

        botonDesplegar.setBackground(new java.awt.Color(0, 0, 0));
        botonDesplegar.setIcon(new javax.swing.ImageIcon("C:\\Users\\DRA DAMIANYS\\Documents\\NetBeansProjects\\horariosAlumn\\src\\main\\resources\\imag\\flechaabajo.png")); // NOI18N
        botonDesplegar.setBorder(null);
        botonDesplegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDesplegar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDesplegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesplegarActionPerformed(evt);
            }
        });
        jPanel1.add(botonDesplegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 40, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("4");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonDesplegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesplegarActionPerformed
    // Toggle the desplegado flag
    desplegado = !desplegado;

    // Determine which icon to use
    String rutaIcono = desplegado ? "flechaarriba.png" : "flechaabajo.png";
    URL iconoURL = getClass().getResource("/imag/" + rutaIcono);

    System.out.println("Intentando cambiar el ícono a: " + rutaIcono);
    System.out.println("URL cargada: " + iconoURL);

    // Check if the icon URL is valid
    if (iconoURL != null) {
        // Set the new icon
        ImageIcon nuevoIcono = new ImageIcon(iconoURL);
        botonDesplegar.setIcon(nuevoIcono);
        
        // Optionally, force UI update (although this might not be necessary in all cases)
        botonDesplegar.repaint();
    } else {
        System.out.println("❌ Error: No se encontró la imagen en " + rutaIcono);
    }

    // Toggle visibility of maestros
    if (desplegado) {
        horario.mostrarMaestros(numMat);
    } else {
        horario.ocultarMaestros(numMat);
    }

    }//GEN-LAST:event_botonDesplegarActionPerformed
    public void nombreDocente(String docente){
        this.docente=docente;
        jLabel1.setText(docente);
    }
    public void cambiarHoras(){
        jLabel2.setText(String.valueOf(this.horasSem));
    }
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        this.horario.matSelec=this.numMat;
        System.out.println("hola");
    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDesplegar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
